Repository kakao-tech-campus-2nd-step3/Team20_BE, pull requests merged in 2024-09, with the labels that each got.

#3 [#2] init: 프로젝트 생성 및 의존성 추가
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/gamsa/Application.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/gamsa/GamsaApplicationTests.java
Labels: init

#4 merge week3
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/gamsa/Application.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/gamsa/GamsaApplicationTests.java
Labels: init

#7 [#6] feat: 봉사활동 조회 기능 추가
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/controller/ActivityController.java
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/dto/ActivityFindAllResponse.java
  src/main/java/com/gamsa/activity/dto/ActivitySaveRequest.java
  src/main/java/com/gamsa/activity/entity/ActivityJpaEntity.java
  src/main/java/com/gamsa/activity/exception/ActivityAlreadyExistsException.java
  src/main/java/com/gamsa/activity/repository/ActivityRepository.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/common/entity/BaseEntity.java
Labels: feat

#8 weekly: 3주차 작업 내용 머지
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/controller/ActivityController.java
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/dto/ActivityFindAllResponse.java
  src/main/java/com/gamsa/activity/dto/ActivitySaveRequest.java
  src/main/java/com/gamsa/activity/entity/ActivityJpaEntity.java
  src/main/java/com/gamsa/activity/exception/ActivityAlreadyExistsException.java
  src/main/java/com/gamsa/activity/repository/ActivityRepository.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/common/entity/BaseEntity.java
Labels: weekly

#9 deploy: 3주차 작업 내용 배포 브랜치로 병합
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/controller/ActivityController.java
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/dto/ActivityFindAllResponse.java
  src/main/java/com/gamsa/activity/dto/ActivitySaveRequest.java
  src/main/java/com/gamsa/activity/entity/ActivityJpaEntity.java
  src/main/java/com/gamsa/activity/exception/ActivityAlreadyExistsException.java
  src/main/java/com/gamsa/activity/repository/ActivityRepository.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/common/entity/BaseEntity.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/gamsa/GamsaApplicationTests.java
Labels: deploy

#14 fix: PR 템플릿 위치 수정
  .github/pull_request_template.md
  src/test/java/com/gamsa/ApplicationTests.java
Labels: fix

#15 feat: 활동 조회 기능 완성 및 단위테스트 추가
  src/main/java/com/gamsa/activity/controller/ActivityController.java
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/dto/ActivityFindAllResponse.java
  src/main/java/com/gamsa/activity/dto/ActivitySaveRequest.java
  src/main/java/com/gamsa/activity/entity/ActivityJpaEntity.java
  src/main/java/com/gamsa/activity/exception/ActivityAlreadyExistsException.java
  src/main/java/com/gamsa/activity/exception/ActivityCustomException.java
  src/main/java/com/gamsa/activity/repository/ActivityJpaRepository.java
  src/main/java/com/gamsa/activity/repository/ActivityRepositoryImpl.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/auth/SecurityConfig.java
  src/main/java/com/gamsa/common/constant/ErrorCode.java
  src/main/java/com/gamsa/common/exception/GlobalExceptionHandler.java
  src/test/java/com/gamsa/activity/entity/ActivityJpaEntityTest.java
  src/test/java/com/gamsa/activity/repository/ActivityJpaRepositoryTest.java
  src/test/java/com/gamsa/activity/service/ActivityServiceTest.java
  src/test/java/com/gamsa/activity/stub/StubEmptyActivityRepository.java
  src/test/java/com/gamsa/activity/stub/StubExistsActivityRepository.java
Labels: feat

#26 Feat: 아바타 관련 기능 구현
  build.gradle
  src/main/java/com/gamsa/avatar/constant/AgeRange.java
  src/main/java/com/gamsa/avatar/constant/AgeRangeConverter.java
  src/main/java/com/gamsa/avatar/constant/Experienced.java
  src/main/java/com/gamsa/avatar/constant/ExperiencedConverter.java
  src/main/java/com/gamsa/avatar/controller/AvatarController.java
  src/main/java/com/gamsa/avatar/domain/Avatar.java
  src/main/java/com/gamsa/avatar/dto/AvatarFindResponse.java
  src/main/java/com/gamsa/avatar/dto/AvatarSaveRequest.java
  src/main/java/com/gamsa/avatar/entity/AvatarJpaEntity.java
  src/main/java/com/gamsa/avatar/repository/AvatarJpaRepository.java
  src/main/java/com/gamsa/avatar/repository/AvatarRepository.java
  src/main/java/com/gamsa/avatar/repository/AvatarRepositoryImpl.java
  src/main/java/com/gamsa/avatar/service/AvatarService.java
  src/test/java/com/gamsa/avatar/entity/AvatarJpaEntityTest.java
  src/test/java/com/gamsa/avatar/repository/AvatarJpaRepositoryTest.java
  src/test/java/com/gamsa/avatar/service/AvatarServiceTest.java
  src/test/java/com/gamsa/avatar/stub/StubAvatarRepository.java
Labels: feat
