Repository kakao-tech-campus-2nd-step3/Team20_BE, pull requests merged in 2024-11, with the labels that each got.

#61 infra: MySQL 연동 및 테스트
  build.gradle
Labels: infra

#63 weekly: 9주차 작업 내용 최종 병합
  .gitignore
  build.gradle
  scripts/deploy.sh
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/domain/District.java
  src/main/java/com/gamsa/activity/dto/ActivityApiResponse.java
  src/main/java/com/gamsa/activity/dto/DistrictSaveRequest.java
  src/main/java/com/gamsa/activity/dto/InstituteApiResponse.java
  src/main/java/com/gamsa/activity/dto/InstituteSaveRequest.java
  src/main/java/com/gamsa/activity/entity/DistrictJpaEntity.java
  src/main/java/com/gamsa/activity/service/DistrictService.java
  src/main/java/com/gamsa/activity/service/InstituteService.java
  src/main/java/com/gamsa/dataupdate/DataUpdateErrorCode.java
  src/main/java/com/gamsa/dataupdate/DataUpdateException.java
  src/main/java/com/gamsa/dataupdate/DataUpdateScheduler.java
  src/main/java/com/gamsa/dataupdate/service/ActivityDataUpdateService.java
  src/main/java/com/gamsa/dataupdate/service/DistrictDataUpdateService.java
  src/main/java/com/gamsa/dataupdate/utils/ActivityDataUtils.java
  src/main/java/com/gamsa/dataupdate/utils/KakaoLocalUtils.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/district_and_coordinate_kr.csv
  src/test/java/com/gamsa/dataupdate/ActivityDataUtilsTest.java
  src/test/java/com/gamsa/dataupdate/DataUpdateSchedulerTest.java
  src/test/java/com/gamsa/dataupdate/KakaoLocalUtilsTest.java
Labels: weekly

#64 deploy: 9주차 작업 내용 배포
  .gitignore
  build.gradle
  scripts/deploy.sh
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/domain/District.java
  src/main/java/com/gamsa/activity/dto/ActivityApiResponse.java
  src/main/java/com/gamsa/activity/dto/DistrictSaveRequest.java
  src/main/java/com/gamsa/activity/dto/InstituteApiResponse.java
  src/main/java/com/gamsa/activity/dto/InstituteSaveRequest.java
  src/main/java/com/gamsa/activity/entity/DistrictJpaEntity.java
  src/main/java/com/gamsa/activity/service/DistrictService.java
  src/main/java/com/gamsa/activity/service/InstituteService.java
  src/main/java/com/gamsa/dataupdate/DataUpdateErrorCode.java
  src/main/java/com/gamsa/dataupdate/DataUpdateException.java
  src/main/java/com/gamsa/dataupdate/DataUpdateScheduler.java
  src/main/java/com/gamsa/dataupdate/service/ActivityDataUpdateService.java
  src/main/java/com/gamsa/dataupdate/service/DistrictDataUpdateService.java
  src/main/java/com/gamsa/dataupdate/utils/ActivityDataUtils.java
  src/main/java/com/gamsa/dataupdate/utils/KakaoLocalUtils.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/district_and_coordinate_kr.csv
  src/test/java/com/gamsa/dataupdate/ActivityDataUtilsTest.java
  src/test/java/com/gamsa/dataupdate/DataUpdateSchedulerTest.java
  src/test/java/com/gamsa/dataupdate/KakaoLocalUtilsTest.java
Labels: deploy

#67 [#55] feat: Review 기능 구현
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/history/dto/HistoryFindSliceResponse.java
  src/main/java/com/gamsa/history/service/HistoryService.java
  src/main/java/com/gamsa/review/domain/Answer.java
  src/main/java/com/gamsa/review/domain/Review.java
  src/main/java/com/gamsa/review/dto/ReviewResponse.java
  src/main/java/com/gamsa/review/entity/AnswerJpaEntity.java
  src/main/java/com/gamsa/review/entity/QuestionJpaEntity.java
  src/main/java/com/gamsa/review/entity/ReviewJpaEntity.java
  src/main/java/com/gamsa/review/repository/AnswerJpaRepository.java
  src/main/java/com/gamsa/review/repository/QuestionJpaRepository.java
  src/main/java/com/gamsa/review/repository/ReviewJpaRepository.java
  src/main/java/com/gamsa/review/repository/ReviewRepository.java
  src/main/java/com/gamsa/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/gamsa/review/service/ReviewService.java
  src/test/java/com/gamsa/history/service/HitstoryServiceTest.java
  src/test/java/com/gamsa/review/stub/StubAnswerRepository.java
  src/test/java/com/gamsa/review/stub/StubQuestionRepository.java
  src/test/java/com/gamsa/review/stub/StubReviewRepository.java
Labels: feat

#68 weekly: 10주차 작업 내용 머지
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/history/dto/HistoryFindSliceResponse.java
  src/main/java/com/gamsa/history/service/HistoryService.java
  src/main/java/com/gamsa/review/controller/QuestionController.java
  src/main/java/com/gamsa/review/controller/ReviewController.java
  src/main/java/com/gamsa/review/domain/Answer.java
  src/main/java/com/gamsa/review/domain/Question.java
  src/main/java/com/gamsa/review/domain/Review.java
  src/main/java/com/gamsa/review/dto/AnswerSaveRequest.java
  src/main/java/com/gamsa/review/dto/QuestionResponse.java
  src/main/java/com/gamsa/review/dto/ReviewResponse.java
  src/main/java/com/gamsa/review/dto/ReviewSaveRequest.java
  src/main/java/com/gamsa/review/entity/AnswerJpaEntity.java
  src/main/java/com/gamsa/review/entity/QuestionJpaEntity.java
  src/main/java/com/gamsa/review/entity/ReviewJpaEntity.java
  src/main/java/com/gamsa/review/repository/AnswerJpaRepository.java
  src/main/java/com/gamsa/review/repository/AnswerRepository.java
  src/main/java/com/gamsa/review/repository/QuestionJpaRepository.java
  src/main/java/com/gamsa/review/repository/QuestionRepository.java
  src/main/java/com/gamsa/review/repository/QuestionRepositoryImpl.java
  src/main/java/com/gamsa/review/repository/ReviewJpaRepository.java
  src/main/java/com/gamsa/review/repository/ReviewRepository.java
  src/main/java/com/gamsa/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/gamsa/review/service/QuestionService.java
  src/main/java/com/gamsa/review/service/ReviewService.java
  src/test/java/com/gamsa/history/service/HitstoryServiceTest.java
  src/test/java/com/gamsa/review/stub/StubAnswerRepository.java
  src/test/java/com/gamsa/review/stub/StubQuestionRepository.java
  src/test/java/com/gamsa/review/stub/StubReviewRepository.java
Labels: weekly

#69 deploy: 10주차 내용 배포
  src/main/java/com/gamsa/activity/domain/Activity.java
  src/main/java/com/gamsa/activity/dto/ActivityDetailResponse.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/main/java/com/gamsa/history/dto/HistoryFindSliceResponse.java
  src/main/java/com/gamsa/history/service/HistoryService.java
  src/main/java/com/gamsa/review/controller/QuestionController.java
  src/main/java/com/gamsa/review/controller/ReviewController.java
  src/main/java/com/gamsa/review/domain/Answer.java
  src/main/java/com/gamsa/review/domain/Question.java
  src/main/java/com/gamsa/review/domain/Review.java
  src/main/java/com/gamsa/review/dto/AnswerSaveRequest.java
  src/main/java/com/gamsa/review/dto/QuestionResponse.java
  src/main/java/com/gamsa/review/dto/ReviewResponse.java
  src/main/java/com/gamsa/review/dto/ReviewSaveRequest.java
  src/main/java/com/gamsa/review/entity/AnswerJpaEntity.java
  src/main/java/com/gamsa/review/entity/QuestionJpaEntity.java
  src/main/java/com/gamsa/review/entity/ReviewJpaEntity.java
  src/main/java/com/gamsa/review/repository/AnswerJpaRepository.java
  src/main/java/com/gamsa/review/repository/AnswerRepository.java
  src/main/java/com/gamsa/review/repository/QuestionJpaRepository.java
  src/main/java/com/gamsa/review/repository/QuestionRepository.java
  src/main/java/com/gamsa/review/repository/QuestionRepositoryImpl.java
  src/main/java/com/gamsa/review/repository/ReviewJpaRepository.java
  src/main/java/com/gamsa/review/repository/ReviewRepository.java
  src/main/java/com/gamsa/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/gamsa/review/service/QuestionService.java
  src/main/java/com/gamsa/review/service/ReviewService.java
  src/test/java/com/gamsa/history/service/HitstoryServiceTest.java
  src/test/java/com/gamsa/review/stub/StubAnswerRepository.java
  src/test/java/com/gamsa/review/stub/StubQuestionRepository.java
  src/test/java/com/gamsa/review/stub/StubReviewRepository.java
Labels: deploy

#72 feat: 키워드 검색 기능 추가
  src/main/java/com/gamsa/activity/controller/ActivityController.java
  src/main/java/com/gamsa/activity/dto/ActivityFilterRequest.java
  src/main/java/com/gamsa/activity/repository/ActivityFilterBuilder.java
Labels: feat

#76 fix: 잘못된 파일 삭제
  src/main/java/com/gamsa/activtydata/ActivityDataUpdateScheduler.java
  src/main/java/com/gamsa/activtydata/ActivityDataUtils.java
  src/main/java/com/gamsa/activtydata/DistrictDataService.java
  src/main/java/com/gamsa/activtydata/KakaoLocalService.java
Labels: fix

#77 fix: 데이터 수집 관련 코드, 설정, 테스트 수정 및 CI/CD 수정
  .github/workflows/dev-ci.yml
  .github/workflows/prod-ci.yml
  .gitignore
  scripts/deploy.sh
  src/main/java/com/gamsa/dataupdate/DataUpdateScheduler.java
  src/main/java/com/gamsa/dataupdate/service/DistrictDataUpdateService.java
  src/main/java/com/gamsa/dataupdate/utils/ActivityDataUtils.java
  src/main/java/com/gamsa/dataupdate/utils/InputStreamUtils.java
  src/main/java/com/gamsa/dataupdate/utils/KakaoLocalUtils.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/gamsa/activity/repository/ActivityJpaRepositoryTest.java
  src/test/java/com/gamsa/activity/service/ActivityServiceTest.java
  src/test/java/com/gamsa/activity/service/InstituteServiceTest.java
  src/test/java/com/gamsa/dataupdate/ActivityDataUtilsTest.java
  src/test/java/com/gamsa/dataupdate/DataUpdateSchedulerTest.java
  src/test/java/com/gamsa/dataupdate/KakaoLocalUtilsTest.java
Labels: fix

#80 feat: 가까운 거리순 정렬 기능 추가
  src/main/java/com/gamsa/activity/controller/ActivityController.java
  src/main/java/com/gamsa/activity/dto/ActivityFindDistanceOrderRequest.java
  src/main/java/com/gamsa/activity/entity/ActivityJpaEntity.java
  src/main/java/com/gamsa/activity/entity/DistrictJpaEntity.java
  src/main/java/com/gamsa/activity/repository/ActivityCustomRepository.java
  src/main/java/com/gamsa/activity/repository/ActivityCustomRepositoryImpl.java
  src/main/java/com/gamsa/activity/repository/ActivityRepository.java
  src/main/java/com/gamsa/activity/repository/ActivityRepositoryImpl.java
  src/main/java/com/gamsa/activity/service/ActivityService.java
  src/test/java/com/gamsa/activity/repository/ActivityJpaRepositoryTest.java
  src/test/java/com/gamsa/activity/service/ActivityServiceTest.java
  src/test/java/com/gamsa/activity/stub/StubEmptyActivityRepository.java
  src/test/java/com/gamsa/activity/stub/StubExistsActivityRepository.java
Labels: feat

#85 weekly: 수정 내용 반영
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/controller/ActivityController.java
Labels: fix

#86 deploy: 11주차 수정 내용 배포
  src/main/java/com/gamsa/Application.java
  src/main/java/com/gamsa/activity/controller/ActivityController.java
Labels: deploy

#87 deploy: 리뷰 관련 수정 버전 배포
  src/main/java/com/gamsa/common/config/WebConfig.java
  src/main/java/com/gamsa/review/controller/ReviewController.java
  src/main/java/com/gamsa/review/domain/Answer.java
  src/main/java/com/gamsa/review/domain/Review.java
  src/main/java/com/gamsa/review/dto/AnswerSaveRequest.java
  src/main/java/com/gamsa/review/entity/AnswerJpaEntity.java
  src/main/java/com/gamsa/review/entity/ReviewJpaEntity.java
  src/main/java/com/gamsa/review/service/ReviewService.java
  src/main/resources/district_and_coordinate_kr.csv
Labels: deploy

#88 deploy: Answer 중복 저장 문제 CASCADE로 해결
  src/main/java/com/gamsa/review/domain/Answer.java
  src/main/java/com/gamsa/review/service/ReviewService.java
  src/test/java/com/gamsa/activity/service/ActivityServiceTest.java
Labels: deploy
